### ISSUE TITLE
Display impl panics on Wasm targets

### ISSUE THREAD

**Issue by palkerecsenyi** [jakudlaty/tsid#27]
Thanks for this library @jakudlaty, it's very helpful!

I'm trying to stringify `TSID` struct instances on a `wasm32-unknown-unknown` target, but the call panics:

```
tsid-0.2.0/src/tsid/display.rs:10:29:
attempt to shift right with overflow
```

Indeed the function implementation currently is shifting by more bits than are available in a `usize` on a 32-bit system:

```rust
...
let number = self.number as usize;
chars.push(ALPHABET[(number >> 60) & 0b11111]);
...
```

I'm not familiar with the details of how TSID serialization works so unfortunately I'm not sure what an immediate simple fix for this would be, but I will look into it.

Thanks again!

**Comment by palkerecsenyi** [comment]
It's not super neat, but something like this seems to fix it:

```rust
impl Display for TSID {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let mut chars = String::with_capacity(13);

        chars.push(ALPHABET[((self.number >> 60) & 0b11111) as usize]);
        chars.push(ALPHABET[((self.number >> 55) & 0b11111) as usize]);
        // ...
   }
}
```

**Comment by jakudlaty** [comment]
Hi
Thank for finding this, i will check Your solution tomorrow. 

About serialization: TSID can be serilized in two ways: 
- in human readable form (usable in json)
- as 64bit unsigned integer value - usable for databases

I will check your fix and update types accordingly to properly support wasm target

**Comment by jakudlaty** [comment]
should be fixed in 0.3.1

**Comment by jakudlaty** [comment]
Please confirm if its working for You

**Comment by palkerecsenyi** [comment]
Hi @jakudlaty!

Thanks for the fix and sorry for the delay, this is working perfectly!

Thanks so much
